### ISSUE TITLE
The API can't give back more than 40k results.

### ISSUE THREAD

**Issue by georgetardy** [facebookresearch/Ad-Library-API-Script-Repository#1]
Either I run this script or use my own solution, I just can't get more than 40 thousand results back. After reaching 40k records, the API drops an exception: {"code": 1, "message": "An unknown error occurred"}]

Is there a way to fix this?

Thanks

**Comment by colin-fraser** [comment]
Can you provide an example query that fails?

**Comment by georgetardy** [comment]
python3.7 fb_ads_library_api_cli.py -t EAAkJfhDJvucBAF2kQh8yEAZADpJQ1w3pJyP4bkzfzVjq7MeiaaYaM70yXy3mywBH2hhHfeQdYR9q2EZBmCl4ygQ5mYmXxT64gE78sZBhhkT5qqFEVXdiDqs5KI2PHfw6cxkZA5kpTmZBH8hMIT1jKg8Te2DQTMCJY7UXjhbZAUZBDs7KxRvST8Sn6Of0sR74DIAjoYOcJ1UDZAakaxyOmkUv -f 'page_id,ad_snapshot_url,funding_entity,ad_delivery_start_time' -c 'HU' -s '""' --ad-active-status 'ALL' --batch-size '5000' -v save 'output-Feb-16-2020.json'

**Comment by georgetardy** [comment]
However, I just realized that if I'm using a smaller batch size, e.g. '500' the script runs fine and paging works OK beyond 40k hits...

**Comment by georgetardy** [comment]
After some trial and error I figured out that a max limit of 4470 is still OK. Use anything above that and the API's going to drop the Code 1 exception.

**Comment by cherylskylar** [comment]
@georgetardy has this issue persisted for you?

**Comment by rinogo** [comment]
@georgetardy - You should regenerate your access token since it's posted for the world to see above! 😬
