### ISSUE TITLE
Any update following to release note?

### ISSUE THREAD

**Issue by ujeong1** [facebookresearch/Ad-Library-API-Script-Repository#14]
Hi,

I found that some parameters are not updated to the recent Graph API version (e.g., 13.0) which includes funding entity, ad_creativity_ body, etc. Do you have any plan to manage this repository?

Best,

**Comment by rinogo** [comment]
@ujeong1 You can just remove the deprecated fields from your command. I believe the fields that are supported in 14.0 are:
```
-f 'ad_creation_time,ad_creative_bodies,ad_creative_link_captions,ad_creative_link_descriptions,ad_creative_link_titles,ad_delivery_start_time,ad_delivery_stop_time,ad_snapshot_url,currency,delivery_by_region,demographic_distribution,id,impressions,languages,page_id,page_name,publisher_platforms,spend'
```
