### ISSUE TITLE
Application does not have permission for this action. Can't get account verified.

### ISSUE THREAD

**Issue by freiheit950** [facebookresearch/Ad-Library-API-Script-Repository#15]
My FB account has completed the verification process, it looks complete, but I never got a chance to request a code (the one that is mailed to you) and now I can't access this part of the API because I get "Application does not have permission for this action" which supposedly happens when your account is not fully verified.

Does anybody know where or how to request the code so they can mail it to you? Or what other issue could be causing this error message....

**Comment by jm-yu** [comment]
That error message usually means the user need to confirm their ID. 

According to the instructions in the Ad Library API landing page(https://www.facebook.com/ads/library/api). You should be able to request the code in facebook.com/id.

**Comment by freiheit950** [comment]
@jm-yu the id page says my account is verified, but I see no option to request a code to be mailed to my address, this has been the issue

**Comment by jm-yu** [comment]
@freiheit950 This is not an issue for this github repo. You can probably create a bug report on (facebook.com/id) or seek help from https://www.facebook.com/business/help
