### ISSUE TITLE
App permissions and features clarification

### ISSUE THREAD

**Issue by gturke** [facebookresearch/Ad-Library-API-Script-Repository#18]
Can you please clarify what app permissions and features are needed to access ads library data via the API? I'm very confused trying to debug failures. I don't know if I'm doing something wrong or if I don't have the permissions and features needed to access the ads library via the graph API.

**Comment by jm-yu** [comment]
For ad library api related permission, It is documented in the ad library api page(https://www.facebook.com/ads/library/api). Step 1 to Step 3. 

If you will get an error about something is wrong with the permission. It may come from the general meta api permission requirement or the ad library api permission. The error code and error message should be different.

**Comment by gturke** [comment]
Thank you @jm-yu - I had to get a notarized document and then that resolved my issue.
