### ISSUE TITLE
How to find page ids from URL?

### ISSUE THREAD

**Issue by NickCrews** [facebookresearch/Ad-Library-API-Script-Repository#25]
I'm trying to look at the ads run by specific pages (~200 of them). I have these in the form of URLs of pages.

I have this working once I have the page id, but I can't figure out an automated way of finding the page id from a URL.

Any tips?

Thank you!

**Comment by hcych1** [comment]
Hi Nick, unfortunately, the Ad Library API does not have the capability to convert page URL's to page ID's

**Comment by NickCrews** [comment]
I ended up writing my own scraper as a workaround: https://gist.github.com/NickCrews/207888d33020b8fada4908f8be8dd930
