### ISSUE TITLE
Why is only POLITICAL_AND_ISSUE_ADS available for ad_type?

### ISSUE THREAD

**Issue by sabetAI** [facebookresearch/Ad-Library-API-Script-Repository#9]
![image](https://user-images.githubusercontent.com/28828395/127408875-c900dfbe-16a1-4cb4-b0de-c3d959c77f2e.png)
https://www.facebook.com/ads/library/api/

**Comment by ashlinnn** [comment]
This is as designed for the API especially since a lot of the data returned is POLITICAL_AND_ISSUE_ADS related only. Additionally, we currently do not expose data for inactive non-political ads even in the Ad Library.
